src/java/model/Project.java
package model;

import java.util.ArrayList;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import dao.TimeAgo;

public class Project {

    private int id;
    private String title;
    private int creator_id;
    private int assigned_user_id;
    private Date created_at;
    private Date updated_at;
    private ArrayList<Task> task = new ArrayList<>();
    String Status;
    String time_status;
    long interval;
    String ago;
    String create_time;
    String manager;
    String developer;

    public String getManager() {
        return manager;
    }

    public void setManager(String manager) {
        this.manager = manager;
    }

    public String getDeveloper() {
        return developer;
    }

    public void setDeveloper(String developer) {
        this.developer = developer;
    }

    public String getTime_status() {
        return time_status;
    }

    public String getAgo() {
        return ago;
    }

    public void setAgo(String ago) {
        this.ago = ago;
    }

    public void setTime_status(String time_status) {
        this.time_status = time_status;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }
    

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getCreator_id() {
        return creator_id;
    }

    public void setCreator_id(int creator_id) {
        this.creator_id = creator_id;
    }

    public int getAssigned_user_id() {
        return assigned_user_id;
    }

    public void setAssigned_user_id(int assigned_user_id) {
        this.assigned_user_id = assigned_user_id;
    }


    public Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    public void setTask(ArrayList<Task> task) {
        this.task = new ArrayList<>(task);
    }
   public ArrayList<Task> getTask(){
    
        return this.task;
    }
       public void setCreated_at(Date d) {
        this.created_at = d;
        this.setInterval();
        this.setAgo();
        this.setStatus();
    }


    public void setInterval() {
        Date d = new Date();
        long t = d.getTime() - created_at.getTime();
        this.interval = t;
    }

    public void setAgo() {
        this.ago = TimeAgo.toDuration(interval);

    }

    public void setStatus() {
        if(this.interval <15000)
            this.Status = "new";
        else if(this.interval<30000)
            this.Status = "old";
        else
            this.Status="expired" ;
    }
    

}

src/java/controller/ProjectController.java
package controller;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import dao.ProjectDao;
import dao.UserDao;
import java.util.ArrayList;
import javax.servlet.http.HttpSession;
import model.Project;

/**
 *
 * @author monirulalom
 */
public class ProjectController extends HttpServlet {

    private ProjectDao projectdao;
    private UserDao userdao;

    public ProjectController() {
        super();
        projectdao = new ProjectDao();
        userdao = new UserDao();
    }

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession();
        int uid = (Integer) session.getAttribute("user_id");
        String action = request.getParameter("action");
        String role = (String) session.getAttribute("user_role");
        if (action.equalsIgnoreCase("view")) {

            try {

                //  
                if (role.equalsIgnoreCase("developer")) {
                    request.setAttribute("projects", projectdao.getProjectListByUser(uid));
                } else {
                    request.setAttribute("projects", projectdao.getProjectList());
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

            RequestDispatcher view = request.getRequestDispatcher("project/projects.jsp");
            view.forward(request, response);

        }
        if (action.equalsIgnoreCase("add")) {
            try {

                request.setAttribute("users", userdao.getUserlist());

            } catch (Exception e) {
                e.printStackTrace();
            }

            RequestDispatcher view = request.getRequestDispatcher("project/project.jsp");
            view.forward(request, response);
        }
        if (action.equalsIgnoreCase("delete")) {
            int id = Integer.parseInt(request.getParameter("id"));

            projectdao.removeProject(id);

            response.sendRedirect("projects?action=view");
        }
        if (action.equalsIgnoreCase("edit")) {
            int id = Integer.parseInt(request.getParameter("id"));
            try {
                request.setAttribute("project", projectdao.getProjectById(id));
                request.setAttribute("users", userdao.getUserlist());
            } catch (SQLException e) {
                e.printStackTrace();
            }

            RequestDispatcher view = request.getRequestDispatcher("project/editProject.jsp");
            view.forward(request, response);
        }
        if (action.equalsIgnoreCase("task")) {
            try {
                request.setAttribute("id", request.getParameter("id"));
            } catch (Exception e) {
                e.printStackTrace();
            }

            RequestDispatcher view = request.getRequestDispatcher("Task/task.jsp");
            view.forward(request, response);
        }

    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        String title = request.getParameter("title");
        int user = Integer.parseInt(request.getParameter("user"));
        int id = Integer.parseInt(request.getParameter("id"));
        int creator = Integer.parseInt(request.getParameter("creator"));
        String update = request.getParameter("update");

        Project project = new Project();
        project.setTitle(title);
        project.setAssigned_user_id(user);
        project.setCreator_id(creator);
        project.setId(id);

        if (update.equalsIgnoreCase("true")) {
            projectdao.updateProject(project);
        } else {

            projectdao.addProject(project);
        }

        response.sendRedirect("projects?action=view");
    }

}

web/project/editProject.jsp
<%-- 
    Document   : project
    Created on : Mar 8, 2020, 11:20:16 PM
    Author     : monirulalom
--%>


<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<% // if(request.getAttribute("users") == null) response.sendRedirect("facebook.com"); %>
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
        <title>Edit Project</title>
        <link href="/jsplogin/bootstrap.css" rel="stylesheet">
        <link href="/jsplogin/style.css" rel="stylesheet">
    </head>
    <body>


        <div class="container">
            <h2 class="text-center">Update project </h2>

            <form action="projects" method="POST" class="form-signin">
                <div class="form-group">
                    <label for="title" >Project Title</label>
                    <input type="text" name="title" class="form-control" placeholder="Project title" value="${project.title}">
                </div>
                <div class="form-group">
                    <label for="user" >Developer</label>
                    <select name="user" class="form-control">
                        <c:forEach items="${users}" var="user">
                            <option value="${user.id}">${user.email}</option>
                        </c:forEach> 
                    </select>
                </div>
                <input type="hidden" value="<c:out value="${sessionScope.user_id}"/>" name="creator"  class="form-control">
                 <input type="hidden" value="<c:out value="${project.id}"/>" name="id"  class="form-control">
                <input type="hidden" value="true" name="update">
                <input  class="btn btn-lg btn-primary btn-block" type="submit" value="Update">
            </form>
    </body>
</html>

web/project/project.jsp
<%-- 
    Document   : project
    Created on : Mar 8, 2020, 11:20:16 PM
    Author     : monirulalom
--%>


<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<% // if(request.getAttribute("users") == null) response.sendRedirect("facebook.com"); %>
  <%  String a = (String) session.getAttribute("user_role"); if (! a.equalsIgnoreCase("manager")) { response.sendRedirect("unauthorized.jsp");}%>
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
        <title>Add Project</title>
        <link href="/jsplogin/bootstrap.css" rel="stylesheet">
        <link href="/jsplogin/style.css" rel="stylesheet">
    </head>
    <body>


        <div class="container">
            <h2 class="text-center">Add Project </h2>

            <form action="projects" method="POST" class="form-signin">
                <div class="form-group">
                    <label for="title" >Project Title</label>
                    <input type="text" name="title" class="form-control" placeholder="Project title">
                </div>
                <div class="form-group">
                    <label for="user" >Developer</label>
                    <select name="user" class="form-control">
                        <c:forEach items="${users}" var="user">
                            <option value="${user.id}">${user.email}</option>
                        </c:forEach> 
                    </select>
                </div>
                <input type="hidden" value="<c:out value="${sessionScope.user_id}"/>" name="creator">
                <input type="hidden" value="100" name="id">
                <input type="hidden" value="false" name="update">
                <input  class="btn btn-lg btn-primary btn-block" type="submit" value="Add">
            </form>
    </body>
</html>

web/project/projects.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
         pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!doctype html>
<%  if (null == session.getAttribute("user_id")) {
        response.sendRedirect("unauthorized.jsp");
    }%>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
        <title>Project Management System</title>
        <link href="/jsplogin/bootstrap.css" rel="stylesheet">
        <link href="/jsplogin/style.css" rel="stylesheet">
    </head>
    <body style="display: block">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="#">Project Management System</a>
            <div class="center"><c:out value="${sessionScope.user_email}" /></div>
            <div class="right"><a class="navbar-brand" href="logout.jsp">Log out</a></div>

        </nav>



        <div class="wrap">

            <h2 class="text-center">Projects </h2>
            <%  String a = (String) session.getAttribute("user_role");
            if (a.equalsIgnoreCase("manager")) { %>
            <a class="btn btn-primary" style="margin:10px" href="projects?action=add">Add Project</a>
            <%}%>

            <section>
                <c:forEach items="${projects}" var="project">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h3 class="card-title">${project.title}</h3>
                            <p class="card-text">Manager: ${project.manager}
                                <br> Developer:  ${project.developer}
                                <br> Created: ${project.ago}</p>
                            <br>Tasks for this project </div>
                                
                        <ul class="list-group list-group-flush">
                            <c:forEach  items="${project.task}" var="task">
                                <li class="list-group-item"><span class="half"><c:out value="${task.title}"></c:out></span><span class="half"> <a title="Mark as completed" class="<c:if test="${task.status == 'completed'}">highlight</c:if>" href="tasks?id=${task.id}&status=completed">Completed</a><a  title="Mark as reviewed" class="<c:if test="${task.status == 'reviewed'}">highlight</c:if>" href="tasks?id=${task.id}&status=reviewed">Reviewed</a></span></li>
                                    </c:forEach>
                        </ul>
                            <% if (a.equalsIgnoreCase("manager")) { %>
                        <div class="card-body">
                            <a href="projects?action=task&id=${project.id}" class="card-link">Add Task</a>
                            <a href="projects?action=edit&id=${project.id}" class="card-link">Edit</a>
                            <a href="projects?action=delete&id=${project.id}" class="card-link">Delete</a>
                        </div>
                            <%} %>
                    </div>
                </c:forEach>
            </section>	
        </div>

    </body>
</html>
<%%>